name: deploy NextjsFE to DO

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: PUSH FE TO DO
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: executing remote ssh commands using ssh
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: 68.183.93.214
                username: root
                passphrase: ${{ secrets.PASSPHRASE }} 
                key: ${{ secrets.SSHKEY }}
                port: 22
                script: |
                    whoami
                    ls
                    pwd
                    cd ci-app/ci-practice-app
                    if [ ! -d "$ci-app" ]; then
                    echo "$ci-ap does not exist."
                    mkdir ci-app
                    cd ci-app
                    git init
                    git clone https://github.com/lomash-choudhary/ci-practice-app.git 
                    cd ci-practice-app
                    fi
                    git pull
                    npm install
                    npm run build
                    pm2 stop all || true
                    pm2 start npm --name "next-app" -- run start


